version: '3.8'

services:
  monitoring_backend:
    build: .
    container_name: 2jz-monitoring-backend
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./backend:/app/backend
    restart: unless-stopped