name: 2jzgte-monitoring
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - flask
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - gunicorn
  - pip
  - pip:
      - python-dotenv