name: 2jz-monitoring
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - flask
  - requests
  - pip:
    - obd
    - tensorflow
    - pyserial